"""Remove method from Forecast

Revision ID: 2bd3f3778126
Revises: 3512cb5c3003
Create Date: 2025-07-22 19:58:23.742354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd3f3778126'
down_revision = '3512cb5c3003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast', schema=None) as batch_op:
        batch_op.drop_column('method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
