"""init database

Revision ID: 3512cb5c3003
Revises: d87c1401d16b
Create Date: 2025-07-22 19:46:43.671888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3512cb5c3003'
down_revision = 'd87c1401d16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('params')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
